server:
  port: 8005

spring:
  application:
    name: cloud-consul-payment-service
  #consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}