server:
  port: 10020

spring:
  application:
    name: dn-nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.79.150:8848
#        ip: 127.0.0.1
      username: nacos
      password: nacos
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# spring boot actuator
management:
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always