server:
  port: 8007
spring:
  application:
    name: cloud-provider-payment-hystrix-service

eureka:
  instance:
    #访问路径可以显示ip
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的实际间隔，单位为秒（默认为30秒）
    lease-renewal-interval-in-seconds: 20
    #Eureka服务端收到最后一次心跳后等待时间上线，单位为秒（默认为90秒） 超时将剔除服务
    lease-expiration-duration-in-seconds: 10
    instance-id: payment-service-8001
  #    ip-address:
  #    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
