server:
  port: 8089
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: config-server-mysql

spring:
  profiles:
    active: jdbc
  application:
    name: config-server-mysql
  datasource:
    username: root
    password: root123456
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb
  cloud:
    refresh:
      enabled: true
    config:
      server:
        default-label: main
        jdbc:
          sql: SELECT config_key, config_value from properties where application=? and config_profile=? and label=?

logging:
  level:
    org.springframework.data.jpa: DEBUG
    root: debug