server:
  port: 8080
spring:
  application:
    name: cloud-registry-consul-consumer
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      config:
        enabled: false
      discovery:
        heartbeat:
          enabled: true


