server:
  port: 80
spring:
  application:
    name: cloud-consumer-order-service
    #consul注册中心地址
eureka:
  instance:
    instance-id: order-service-80
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
logging:
  level:
    com.msr.cloudv2.order.client.PaymentClient: debug